### ISSUE TITLE
feat: gitbook implementation of the contracts, calls and inner mechanics of the protocol

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-contracts#13]
Proposal:
Use gitbook to create comprehensive documentation about the dApp. 
-Develop the layout
-Describe functions
-Describe Interfaces
-Describe typescript used to call the function

**Comment by RafaDSan** [comment]
I am starting this task on 09/10/2023

**Comment by 0xneves** [comment]
I think it's time to release the GitBook on how to use the contract features from a developer's perspective.

I'll jump in this task as well with the help of @Guboehm and @RafaDSan

**Comment by 0xneves** [comment]
We are delayed on this task and I have some news! We should follow this [PR](https://github.com/blockful-io/swaplace-contracts/pull/109) to do the same here! Apply some adjustments and move to gitbook. Let's sync next week

**Comment by RafaDSan** [comment]
[Gitbook online!](https://web3task.gitbook.io/web3task/official-web3task-documentation/introducing-web3task). The Web3Dev team does not have access to this version, so [@annabida and I are migrating this gitbook to the Web3Dev gitbook](https://github.com/orgs/w3b3d3v/projects/6/views/2?filterQuery=rafad&pane=issue&itemId=50466708), so that the team have full access.
If you'd like to change anything on the gitbook, please let us know! @0xneves

**Comment by 0xneves** [comment]
Let's do a review together this thursday! @RafaDSan

**Comment by RafaDSan** [comment]
> Let's do a review together this thursday! [@RafaDSan](https://github.com/RafaDSan)
Sounds great! @0xneves 
https://web3task.gitbook.io/web3task/

**Comment by Guboehm** [comment]
Revised task and gitbook published at the link: [Gitbook Web3Task](https://links.w3d.community/web3task/official-documentation/introducing-web3task)

**Comment by Guboehm** [comment]
@annabida can you update the intro, please

**Comment by annabida** [comment]
ready @Guboehm, update done.  
https://links.w3d.community/web3task/official-documentation/introducing-web3task

**Comment by annabida** [comment]
sorry for the delay

**Comment by Guboehm** [comment]
ok, thanks
