### ISSUE TITLE
doc: Track the main deployed contracts addresses in the README.md

### ISSUE THREAD

**Issue by RafaDSan** [w3b3d3v/web3task-contracts#49]
Add the addresses of the contracts deployed to the blockchain (mainnet or testnet) inside a section in the README.md file.

**Comment by 0xneves** [comment]
Bumping this! We should add them when the final testnet version is deployed since it this version allows anyone to be the admin for test purposes. It was also proposed in the #50 , and there is a minor readme conflict with the #45 which already implements #50. So I will close #50 and move this to TODO until we have for sure the contract addresses.

**Comment by Guboehm** [comment]
Readme updated with the mvp version of the contract
